// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"blumer-ms-refers/handler"
)

// Injectors from wire.go:

func Initialize() (*handler.Handler, error) {
	neoSession, err := providerNeoSession()
	if err != nil {
		return nil, err
	}
	repository, err := providerRepository(neoSession)
	if err != nil {
		return nil, err
	}
	consumer, err := providerKafkaConsumer()
	if err != nil {
		return nil, err
	}
	kafkaReducer := providerReducer(repository, consumer)
	producer, err := providerKafkaProducer()
	if err != nil {
		return nil, err
	}
	kafkaProducer := providerAggregation(producer)
	handlerHandler, err := providerHandler(repository, kafkaReducer, kafkaProducer)
	if err != nil {
		return nil, err
	}
	return handlerHandler, nil
}
